data = [
    {'name': 'Elon Musk', 'followers': 186124856, 'description': 'Businessman', 'country': 'U.S.A'},
    {'name': 'Barack Obama', 'followers': 110890048, 'description': 'Politician', 'country': 'U.S.A'},
    {'name': 'KATY PERRY', 'followers': 108315414, 'description': 'Musician', 'country': 'U.S.A'},
    {'name': 'Justin Bieber', 'followers': 107410873, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Rihanna', 'followers': 94990708, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Taylor Swift', 'followers': 85520236, 'description': 'Musician', 'country': 'U.S.A'},
    {'name': 'Cristiano Ronaldo', 'followers': 81657805, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lady Gaga', 'followers': 80566835, 'description': 'Musician and actress', 'country': 'U.S.A'},
    {'name': 'Ellen DeGeneres', 'followers': 79184882, 'description': 'Comedian', 'country': 'U.S.A'},
    {'name': 'YouTube', 'followers': 72137278, 'description': 'Online Video Platform', 'country': 'U.S.A'},
    {'name': 'Ariana Grande', 'followers': 68242627, 'description': 'Musician and actress', 'country': 'U.S.A'},
    {'name': 'Donald J. Trump', 'followers': 67876680, 'description': 'Politician', 'country': 'U.S.A'},
    {'name': 'Justin Timberlake', 'followers': 65035521, 'description': 'Musician and actor', 'country': 'U.S.A'},
    {'name': 'Kim Kardashian West', 'followers': 62672213, 'description': 'Television personality and businesswoman', 'country': 'U.S.A'},
    {'name': 'Selena Gomez', 'followers': 59213665, 'description': 'Musician and actress', 'country': 'U.S.A'},
    {'name': 'Twitter', 'followers': 56874310, 'description': 'Social Media Platform', 'country': 'U.S.A'},
    {'name': 'Britney Spears', 'followers': 56234417, 'description': 'Musician', 'country': 'U.S.A'},
    {'name': 'CNN Breaking News', 'followers': 56164938, 'description': 'News Channel', 'country': 'U.S.A'},
    {'name': 'Narendra Modi', 'followers': 52057261, 'description': 'Politician', 'country': 'India'},
    {'name': 'Shakira', 'followers': 51701898, 'description': 'Musician', 'country': 'Columbia'},
    {'name': 'jimmy fallon', 'followers': 51564819, 'description': 'Comedian', 'country': 'U.S.A'},
    {'name': 'Bill Gates', 'followers': 48634021, 'description': 'Businessman and philanthropist', 'country': 'U.S.A'},
    {'name': 'Neymar Jr', 'followers': 44956357, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'The New York Times', 'followers': 44669530, 'description': 'News paper', 'country': 'U.S.A'},
    {'name': 'Miley Ray Cyrus', 'followers': 44642027, 'description': 'Musician and actress', 'country': 'U.S.A'},
    {'name': 'Jennifer Lopez', 'followers': 44245585, 'description': 'Musician and actress', 'country': 'U.S.A'},
    {'name': 'LeBron James', 'followers': 44235848, 'description': 'Basketball Player', 'country': 'U.S.A'},
    {'name': 'CNN', 'followers': 43925167, 'description': 'News Channel', 'country': 'U.S.A'},
    {'name': 'Bruno Mars', 'followers': 43260457, 'description': 'Musician', 'country': 'U.S.A'},
    {'name': 'Oprah Winfrey', 'followers': 42735399, 'description': 'Television personality and businesswoman', 'country': 'U.S.A'},
    {'name': 'BBC Breaking News', 'followers': 41162339, 'description': 'News channel', 'country': 'U.K'},
    {'name': 'Shah Rukh Khan', 'followers': 39555745, 'description': 'Actor', 'country': 'India'},
    {'name': 'Amitabh Bachchan', 'followers': 39517144, 'description': 'Actor', 'country': 'India'},
    {'name': 'Niall Horan', 'followers': 39453141, 'description': 'Singer and songwriter', 'country': 'Ireland'},
    {'name': 'Drake', 'followers': 38781907, 'description': 'Rapper', 'country': 'Canada'},
    {'name': 'Salman Khan', 'followers': 38636377, 'description': 'Actor ', 'country': 'India'},
    {'name': 'Instagram', 'followers': 36155546, 'description': 'Social media platform', 'country': 'U.S.A'},
    {'name': 'SportsCenter', 'followers': 36051596, 'description': 'Sports Channel', 'country': 'U.S.A'},
    {'name': 'Kevin Hart', 'followers': 35906579, 'description': 'Actor', 'country': 'U.S.A'},
    {'name': 'Wiz Khalifa', 'followers': 35408869, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'ESPN', 'followers': 34607272, 'description': 'Sports Channel', 'country': 'U.S.A'},
    {'name': 'Lil Wayne', 'followers': 34553304, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'NASA', 'followers': 34409407, 'description': 'Space Agency', 'country': 'U.S.A'},
    {'name': 'Harry Styles.', 'followers': 33829073, 'description': 'Musician', 'country': 'U.K'},
    {'name': 'Louis Tomlinson', 'followers': 33482751, 'description': 'Musician', 'country': 'U.K'},
    {'name': 'Real Madrid C.F.⚽', 'followers': 33413241, 'description': 'Football Club', 'country': 'Spain'},
    {'name': 'Akshay Kumar', 'followers': 33224137, 'description': 'Actor ', 'country': 'India'},
    {'name': 'Liam', 'followers': 32853871, 'description': 'Musician', 'country': 'U.K'},
    {'name': 'Virat Kohli', 'followers': 32806422, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'P!nk', 'followers': 32182969, 'description': 'Musician', 'country': 'U.S.A'},
    {'name': 'Chris Brown', 'followers': 31508059, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'FC Barcelona', 'followers': 31500293, 'description': 'Football Club', 'country': 'Spain'},
    {'name': 'PMO India', 'followers': 31428706, 'description': 'Politician', 'country': 'India'},
    {'name': 'Sachin Tendulkar', 'followers': 31256938, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'One Direction', 'followers': 30572946, 'description': 'Band', 'country': 'U.K'},
    {'name': 'Alicia Keys', 'followers': 30214865, 'description': 'Musician and Singer', 'country': 'U.S.A'},
    {'name': 'Kylie Jenner', 'followers': 29812968, 'description': 'Media personality', 'country': 'U.S.A'},
    {'name': 'Kaka', 'followers': 29659299, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Kanye West', 'followers': 29443555, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'Emma Watson', 'followers': 29207070, 'description': 'Actor', 'country': 'U.K'},
    {'name': 'NBA', 'followers': 28869000, 'description': 'Basketball League', 'country': 'U.S.A'},
    {'name': "Conan O'Brien", 'followers': 28606148, 'description': 'Television Host', 'country': 'U.S.A'},
    {'name': 'Kendall', 'followers': 28497885, 'description': 'Media personality', 'country': 'U.S.A'},
    {'name': 'Zayn Malik', 'followers': 28471856, 'description': 'Singer', 'country': 'U.K'},
    {'name': 'Khloé Kardashian', 'followers': 27641383, 'description': 'Media personality', 'country': 'U.S.A'},
    {'name': 'Adele', 'followers': 27488867, 'description': 'Singer and songwriter', 'country': 'U.K'},
    {'name': 'President Trump', 'followers': 27344002, 'description': 'Politician', 'country': 'U.S.A'},
    {'name': 'Hrithik Roshan', 'followers': 27002017, 'description': 'Actor', 'country': 'India'},
    {'name': 'Neil Patrick Harris', 'followers': 26862745, 'description': 'Actor', 'country': 'U.S.A'},
    {'name': 'Deepika Padukone', 'followers': 26678189, 'description': 'Actor', 'country': 'India'},
    {'name': 'BBC News (World)', 'followers': 26324451, 'description': 'Television Channel', 'country': 'U.K'},
    {'name': 'Hillary Clinton', 'followers': 26133026, 'description': 'Politician', 'country': 'U.S.A'},
    {'name': 'Pitbull', 'followers': 26030577, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'UEFA Champions League', 'followers': 25970973, 'description': 'Football League', 'country': 'Europe'},
    {'name': 'daniel tosh', 'followers': 25852762, 'description': 'Comedian', 'country': 'Germany'},
    {'name': 'PRIYANKA Chopra', 'followers': 25477964, 'description': 'Actor', 'country': 'India'},
    {'name': 'Aamir Khan', 'followers': 25403135, 'description': 'Actor', 'country': 'India'},
    {'name': 'NFL', 'followers': 24844160, 'description': 'Football League', 'country': 'U.S.A'},
    {'name': 'Kourtney Kardashian', 'followers': 24741721, 'description': 'Media personality', 'country': 'U.S.A'},
    {'name': 'Andrés Iniesta', 'followers': 24583188, 'description': 'Footballer', 'country': 'U.S.A'},
    {'name': 'Mesut Özil', 'followers': 24561230, 'description': 'Footballer', 'country': 'Germany'},
    {'name': 'Shawn Mendes', 'followers': 24451861, 'description': 'singer-songwriter', 'country': 'Canada'},
    {'name': 'The Economist', 'followers': 24208562, 'description': 'News paper', 'country': 'U.K'},
    {'name': 'Coldplay', 'followers': 23703132, 'description': 'Band', 'country': 'U.K'},
    {'name': 'National Geographic', 'followers': 23569469, 'description': 'Television network', 'country': 'U.S.A'},
    {'name': 'BTS', 'followers': 23145832, 'description': 'Band', 'country': 'Korean'},
    {'name': 'Marshall Mathers', 'followers': 22785561, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'A.R.Rahman', 'followers': 22323504, 'description': 'Music Director', 'country': 'India'},
    {'name': 'Google', 'followers': 21651645, 'description': 'Technology company', 'country': 'U.S.A'},
    {'name': 'Avril Lavigne', 'followers': 21546496, 'description': 'singer-songwriter', 'country': 'Canada'},
    {'name': 'Mariah Carey', 'followers': 21402021, 'description': 'singer-songwriter', 'country': 'U.S.A'},
    {'name': 'David Guetta', 'followers': 21237538, 'description': 'DJ', 'country': 'France'},
    {'name': 'Reuters', 'followers': 20966197, 'description': 'News organization company', 'country': 'U.K'},
    {'name': 'Premier League', 'followers': 20948807, 'description': 'Football league', 'country': 'U.K'},
    {'name': 'Manchester United', 'followers': 20757728, 'description': 'Football Club', 'country': 'U.K'},
    {'name': 'Anushka Sharma', 'followers': 20702308, 'description': 'Actor', 'country': 'India'},
    {'name': 'Blake Shelton', 'followers': 20585358, 'description': 'Singer', 'country': 'U.S.A'},
    {'name': 'Nicki Minaj', 'followers': 20543380, 'description': 'Rapper', 'country': 'U.S.A'},
    {'name': 'Ricky Martin', 'followers': 20459564, 'description': 'Singer', 'country': 'Puerto Rico'},
    {'name': 'MohamadAlarefe', 'followers': 20266354, 'description': 'Author', 'country': 'Saudi Arabia'},
]
